# Generated by Django 5.0.2 on 2024-03-16 11:22

import registration.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_businessdetail_business_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='registration_certificate',
            field=models.FileField(upload_to='documents/', validators=[registration.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='tax_compliance_certificate',
            field=models.FileField(upload_to='documents/', validators=[registration.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='trading_license',
            field=models.FileField(upload_to='documents/', validators=[registration.validators.validate_file_extension]),
        ),
    ]
