# Generated by Django 5.0.2 on 2024-03-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_businessdetail_registration_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='phone_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
