# Generated by Django 5.0.2 on 2024-03-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_businessdetail_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
